#!/bin/bash

# Change your default python version if you have more than one installed using deb/ubuntu alternatives
# BECAUSE TYPING COMMANDS IS FOR SQUARES.

if [[ $EUID -ne 0 ]]; then
   echo "GOT ROOT?" 1>&2
   exit 1
fi

update-alternatives --config python
